config/routes.rb
GottaFit::Application.routes.draw do

  get "wait_lists/new"

  get "wait_lists/edit"

  get "wait_lists/index"

  get "slots/new"
  get "slots/calendar"
  get "slots/edit"

  get "slots/create"

  get "slots/destroy"

  get "slots/index"

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users
  resources :slots
  resources :password_resets
  match '/calendars(/:year(/:month))' => 'calendars#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get "static_pages/help"
  get "static_pages/about"

  root :to => 'static_pages#home'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete
  match '/user/:id/confirm/:confirm_code', :to =>'users#confirm'
  match '/users/:id', :via => :post, :to => 'users#edit'
  match '/schedule',  :to => 'slots#index'
  match '/schedule/:view', :to => 'slots#index'

end

app/models/slot.rb
# == Schema Information
#
# Table name: slots
#
#  id         :integer         not null, primary key
#  date       :string(255)
#  start_time :string(255)
#  end_time   :string(255)
#  waiting    :boolean
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  spots      :integer
#
class Slot < ActiveRecord::Base
  attr_accessible :date, :end_time, :start_time, :waiting, :spots, :description
  has_many  :lists, :dependent => :destroy
  has_many  :users, :through => :lists

  before_create {|slot| slot.date = convertdate(date)}
  before_save {|slot| slot.start_time = converttime(start_time)}
  before_save {|slot| slot.end_time = converttime(end_time)}
  after_update :update_lists

  #constants
  VALID_DATE_REGEX = /\d{2}\/\d{2}\/\d{4}/
  VALID_TIME_REGEX = /\d{2}\:\d{2}/
  STATUS_WAITING = "Waiting"
  STATUS_SIGNED_UP = "Signed Up"


  #validation
  validates :date, :presence => true
  validates :start_time, :presence =>  true
  validates :end_time, :presence => true
  validates :spots, :presence => true
  validates :date, :uniqueness => {:scope => [:start_time, :end_time]}

  scope :by_week, lambda { |d| {:conditions =>  {:date => d.beginning_of_week..d.end_of_week}}}
  scope :by_month, lambda { |d| {:conditions => {:date => d.beginning_of_month..d.end_of_month}}}
  scope :by_day, lambda {|d| {:conditions => {:date => d}}}
  scope :by_next_week, lambda { |d| {:conditions =>  {:date => d.beginning_of_week.next_week..d.end_of_week.next_week}}}
  scope :by_next_month, lambda {|d| {:conditions => {:date => d.beginning_of_month.next_month..d.end_of_month.next_month}}}
  scope :by_tomorrow, lambda {|d| {:conditions => {:date => d.tomorrow}}}
  scope :by_year, lambda {|d| {:conditions => {:date => d.beginning_of_year..d.end_of_year}}}

  scope :before, lambda {|end_time| {:conditions => ["end_time < ?", Slot.format_date(end_time)] }}
  scope :after, lambda {|start_time| {:conditions => ["start_time > ?", Slot.format_date(start_time)] }}
  scope :before_date, lambda {|start_date| {:conditions => ["date > ?", start_date] }}
  scope :after_date, lambda {|end_date| {:conditions => ["date < ?", end_date] }}

  #scope :waiting_list, {:conditions => ["state = ? and slot_id = ?", "Waiting", self.id]}
  #scope :signed_up, {:conditions => ["state = ? and slot_id = ?", "Signed Up", self.id]}

  def to_param
    "#{id} #{description}".parameterize
  end

  def waiting_list
    List.where(:state => STATUS_WAITING).where(:slot_id => self.id).order('id ASC')
  end

  def signed_up
    List.where(:state => STATUS_SIGNED_UP).where(:slot_id => self.id).order('id ASC')
  end

  def remove_user(user)
    list = self.lists.where(:user_id => user.id)
    if list[0].state != STATUS_WAITING
      check_wait_list(user)
    end
    if self.users.delete(user)
      user.add_ride unless list[0].state == STATUS_WAITING
      flash = "#{user.name} has been removed from this session"
    else
      flash = "There was a problem removing #{user.name} from this session"
    end
    flash
  end

  def add_user(user)
    if self.available_spots > 0
      state = STATUS_SIGNED_UP
    else
      state = STATUS_WAITING
    end
    if self.users << user
      @list = user.lists.find_by_slot_id(self.id)
      @list.update_attribute('state', state)
      user.remove_ride unless state == STATUS_WAITING
      UserMailer.user_slot_sign_up(user,self).deliver unless state == STATUS_WAITING
      flash  = "#{user.name} is #{state} for session!"
    else
      flash = "There was an issue adding you to the Multi-rider session"
    end
    flash
  end

  def available_spots
    slot_count = self.spots
    slots_taken = self.lists.where(:state => STATUS_SIGNED_UP).count
    slot_count - slots_taken
  end

  def waiting
    self.lists.where(:state => STATUS_WAITING).count
  end

  def signed_up?(user)
    self.users.where(:id => user.id).present?
  end

  private

  def check_wait_list(user)
    list = self.lists.where(:state => STATUS_WAITING).order('updated_at ASC')
    if list.count > 0
      list[0].update_attribute('state', STATUS_SIGNED_UP)
      list[0].user.remove_ride
      #user.remove_ride
      UserMailer.wait_list_notice(list[0].user, self).deliver
    end
  end

  def convertdate(sdate)
    #DateTime.parse(sdate)
    Date.strptime(sdate, '%m/%d/%Y').strftime('%Y-%m-%d')
  end

  def converttime(stime)
    (Time.parse stime).strftime('%H:%M:%S')
  end

  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end

  def update_lists
    #When a slot is edited, check to see if there are available slots
    # and users on the waiting list, if so add waiting to signed up

    #check if there are spots available and users waiting
    if self.available_spots > 0 && self.waiting > 0

      #loop through until spots available are 0 and waiting count is 0
      while self.available_spots > 0 && self.waiting > 0 do
        #create an array of lists where state is waiting for this slot
        #then pick the top one form the list
        list = self.lists.where(:state => STATUS_WAITING).order('id ASC')
        check_wait_list(list[0].user)
      end
    end
  end

end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_filter :admin_check, :only => [:create, :destroy]
  before_filter :sign_in_check

  def new
    @slot = Slot.new
  end

  def edit
    @slot = Slot.find(params[:id])
  end

  def update
    @slot = Slot.find(params[:id])
    if params[:commit] == "Add Me" || params[:commit] == "Join Waiting List" #user adds themselves
      if signed_up?
        flash[:warning] = "you are already signed up for this session"
      else
        flash[:success] = @slot.add_user(current_user)
      end
    elsif params[:commit] == "add/remove rider" #admin adds/removes another user
      user = User.find(params[:all][:users])
      if @slot.signed_up?(user)
        flash[:success] = @slot.remove_user(user) if current_user.admin?
      else
        flash[:success] = @slot.add_user(user) if current_user.admin?
      end
    elsif params[:commit] == "Remove Me" #remove user
      if signed_up?
        flash[:success] =  @slot.remove_user(current_user)
      else
        flash[:notice] = "You are not signed up"
      end
    else
      #update the slot data
      @slot.update_attributes(:description => params[:slot][:description],
                              :start_time => params[:slot][:start_time],
                              :end_time => params[:slot][:end_time],
                              :spots => params[:slot][:spots])
      flash[:success] = "update successful"
    end
    redirect_to @slot
  end

  def create
    @slot = Slot.new(params[:slot])
    if @slot.save
      respond_to do |format|
        format.html {
          flash[:success] = "New rider session created"
          redirect_to '/schedule/weekly'
        }
        format.json {render :json => @slot}
      end
    else
      respond_to do |format|
        format.html {
          flash[:error] = "There was an issue creating the session"
          redirect_to new_slot_path
        }
        format.js {render :json => @slot}
      end
    end
  end

  def destroy
    @remove = Slot.find(params[:id])
    @remove.destroy
    flash[:warning] = "Rider Session removed"
    redirect_to '/schedule/weekly'
  end

  def calendar
    #@slots = Slot.all
    #@slots = Slot.paginate(:page =>  params[:page], :per_page => 7).order('date, start_time ASC').by_month Date.today
    #convert the start_time datetime to string and extract the date and time
    date_format = "%Y-%m-%d"
    time_format = "%H:%M:%S"

    if (params['start_time'])
      s_date = Time.at(params['start_time'].to_i)
      start_date = s_date.strftime(date_format)
      start_time = s_date.strftime(time_format)
    end

    if (params['end_time'])
      e_date = Time.at(params['end_time'].to_i)
      end_date = e_date.strftime(date_format)
      end_time = e_date.strftime(time_format)
    end

    logger.info "start date: " +start_date unless start_date.nil?
    logger.info "start_time:" +start_time unless start_time.nil?
    logger.info "end date: " +end_date unless end_date.nil?
    logger.info "end time: " +end_time unless end_time.nil?

    @slots = Slot.scoped
    @slots = @slots.after_date(end_date) unless end_date.nil?
    @slots = @slots.before_date(start_date) unless start_date.nil?

    @slots = @slots.after(start_time) unless start_time.nil?
    @slots = @slots.before(end_time) unless end_time.nil?
    logger.info @slots.count
    respond_to do |format|
      format.html  { render :html => @slots}
      format.xml  { render :xml => @slots }
      format.js  { render :json => @slots }
    end
  end

  def index
    @slot = Slot.new

    #Detemine the View for Slots Monthly, Weekly, or Daily
    case params[:view]
      when "weekly"
        @slots = Slot.order('date, start_time ASC').by_week Date.today
      when "monthly"
        @slots = Slot.order('date, start_time ASC').by_month Date.today
      when "daily"
        @slots = Slot.order('date, start_time ASC').by_day Date.today
      when "next_week"
        @slots = Slot.order('date, start_time ASC').by_week(Date.today + 7.days)
      when "next_month"
        @slots = Slot.order('date, start_time ASC').by_next_month Date.today
      when "tomorrow"
        @slots = Slot.order('date, start_time ASC').by_tomorrow Date.today
      when "year"
        @slots = Slot.order('date, start_time ASC').by_year Date.today
      else
        @slots = Slot.all(:order => "date, start_time DESC")
    end

    respond_to do |format|
      format.html  { render :html => @slots}
      format.xml  { render :xml => @slots }
      format.js  { render :json => @slots }
    end

  end

  def show
    @slot = Slot.find(params[:id])
    @riders = @slot.signed_up.includes(:user)
    @waiting = @slot.waiting_list.includes(:user)
  end

private

  def admin_check
    unless current_user.admin?
      flash[:warning] = "you are not able to perform this action"
      redirect_to slots_path
    end
  end

  def sign_in_check
    unless signed_in?
      flash[:warning] = "please sign in"
      redirect_to root_path
    end
  end

end

app/helpers/slots_helper.rb
module SlotsHelper

  def showday(sdate)
    Date.strptime(sdate, '%Y-%m-%d' ).strftime('%A %m/%d/%Y')
  end

  def showtime(stime)
    Time.strptime(stime, '%H:%M').strftime('%l:%M %p')
  end

  def signed_up?
    @slot = Slot.find(params[:id])
    @slot.users.where(:id => current_user.id).present?
  end
end

app/views/slots/_admin_add_user.html.erb

<div id="adminAddUser">
  <%= form_for @slot do |f| %>
     <%= collection_select(:all, :users, User.by_last_name, :id, :name) %>
     <%= f.submit "add/remove rider", :class => "btn btn-primary" %>
  <% end %>
</div>

app/views/slots/_fields.html.erb
<div class="row">
  <div id="session_date" class="span5 offset3">
    <%= form_for(@slot) do |f| %>
        <%= render 'shared/errors', object: f.object %>
        <%= f.label :date %>
        <%= f.text_field :date %>

        <%= f.label :start_time %>
        <%= f.text_field :start_time %>

        <%= f.label :end_time %>
        <%= f.text_field :end_time %>

        <%= f.label :spots %>
        <%= f.text_field :spots %>
        <br>
        <%= f.submit "Create", class: "btn btn-large btn-primary" %>

    <% end %>
  </div>
</div>

app/views/slots/_menu.html.erb
<!--<div class="span4 offset1">-->
<div class="span4 pull-left">
  <%= link_to 'This Week', '/schedule/weekly' %> |
  <%= link_to 'This Month', '/schedule/monthly' %> |
  <%= link_to 'Today', '/schedule/daily' %> |
  <%= link_to 'This Year', '/schedule/year' %>
</div>
<!--<div class="span4 offset1 pull-right">-->
<div class="span4 offset2">
  <%= link_to 'Next Week', '/schedule/next_week', :embedded => params[:embedded] %> |
  <%= link_to 'Next Month', '/schedule/next_month' %> |
  <%= link_to 'Tomorrow', '/schedule/tomorrow' %> |
  <%= link_to 'All', '/schedule' %>
</div>

app/views/slots/_new_slot.html.erb
<div class="row" id="new_slot" title="New Session">
  <div id="session_date" class="span2">
    <%= form_for(@slot) do |f| %>
        <%= render 'shared/errors', :object => f.object %>

        <%= f.label :description %>
        <%= f.text_field :description %>

        <%= f.label :date %>
        <%= f.text_field :date %>

        <%= f.label :start_time %>
        <%= f.text_field :start_time %>

        <%= f.label :end_time %>
        <%= f.text_field :end_time %>

        <%= f.label :spots %>
        <%= f.text_field :spots %>
    <% end %>
    <label for="recurring">Recurring?</label>
    <input type="checkbox" value="true" id="recurring">
    <label id="lblRecCount" for="recCount">Number of Weeks</label>
    <input type="textbox" id="recCount">
  </div>
</div>

app/views/slots/_preview_slots.html.erb
<!--<div id='preview' class="span10 offset1">-->

<div id='preview' class="span10">
  <h1>New Slots Added!</h1>
  <table class="table table-condensed table-striped">
    <thead>
    <th>Day</th>
    <th>Description</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th>Total Spots</th>
    <th>Spots Available</th>
    <th>Waiting</th>
    <th></th>
    </thead>
    <tbody id="tblPreviewSlots">
    </tbody>
  </table>
</div>

app/views/slots/_slots_table.html.erb
<!--<div class="span10 offset1">-->
<div class="span10">
  <table class="table table-condensed table-striped" id="tblShowSlots">
    <thead>
    <th>Day</th>
    <th>Description</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th>Total Spots</th>
    <th>Spots Available</th>
    <th>Waiting</th>
    <th></th>
    </thead>
    <tbody id="tblSlots">
    <% @slots.each do |slot|%>
        <tr>
          <td><%= showday(slot.date)%></td>
          <td><%= slot.description %></td>
          <td><%= showtime(slot.start_time)%></td>
          <td><%= showtime(slot.end_time)%></td>
          <td><%= slot.spots %></td>
          <td><%= slot.available_spots %></td>
          <td><%= slot.waiting %></td>
          <td>
            <%= link_to 'View Details', slot%>
            <% if current_user.admin? %>
               | <%= link_to "Remove", slot,:id => "slotRemove" ,:confirm => "Are you sure?", :method => :delete %>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
    </table>

  <% if signed_in? && current_user.admin? %>
      <br><br>
      <a href="#" class="btn btn-primary" id="new">New Session</a>
      <%= render 'new_slot' %>
  <% end %>
</div>

app/views/slots/calendar.html.erb
<% provide(:title, "Calendar of Events") %>

<h2>Multi-Rider Calendar</h2>
<div id='calendar'></div>

app/views/slots/create.html.erb
<h1>Slots#create</h1>
<p>Find me in app/views/slots/create.html.erb</p>

app/views/slots/destroy.html.erb
<h1>Slots#destroy</h1>
<p>Find me in app/views/slots/destroy.html.erb</p>

app/views/slots/edit.html.erb
<%= provide(:title, 'Edit Slot') %>
<div class="row">
  <div class="span12">
    <h4><%= @slot.description %> - edit</h4>
  </div>
</div>
<hr class="style-four">
<div class="row">
  <div class="span12 show-edit">
    <%= form_for @slot, :id => "slot_edit" do |f| %>
        <%= render 'shared/errors', :object => f.object %>
        <%= f.label :description %>
        <%= f.text_field :description %>

        <%= f.label :start_time %>
        <%= f.text_field :start_time %>

        <%= f.label :end_time %>
        <%= f.text_field :end_time %>

        <%= f.label :spots %>
        <%= f.text_field :spots %>
        <br>
        <%= f.submit "Update", :class => "btn btn-large btn-primary" %>

    <% end %>
  </div>
</div>

app/views/slots/index.html.erb
<h4>Multi-rider sessions</h4>
<br>
<%= render 'menu' %>
<hr class="style-four span10">
<!--<div class="container">-->
  <%= render 'slots_table' %>
  <%= render 'preview_slots' %>
<!--</div>-->

app/views/slots/new.html.erb
<% provide(:title, "New Session") %>
<h1>Create New Rider Session</h1>

<div class="row">
  <div id="session_date" class="span5 offset3">
    <%= form_for(@slot) do |f| %>
        <%= render 'shared/errors', :object => f.object %>
        <%= f.label :date %>
        <%= f.text_field :date %>

        <%= f.label :start_time %>
        <%= f.text_field :start_time %>

        <%= f.label :end_time %>
        <%= f.text_field :end_time %>

        <%= f.label :spots %>
        <%= f.text_field :spots %>
        <br>
        <%= f.submit "Create", :class => "btn btn-large btn-primary" %>

    <% end %>
  </div>
</div>

app/views/slots/show.html.erb
<% provide(:title, 'session')%>
<br>
<div class="row span12">
  <h3><%= @slot.description %></h3>
</div><hr>
<div class="row span12">
  <em>Day:</em> <strong><%= showday(@slot.date) %> </strong>
</div><br>
<div class="row span12">
  <em>Start:</em> <strong><%= showtime(@slot.start_time) %> </strong>
</div><br>
<div class="row span12">
  <em>End:</em> <strong><%= showtime(@slot.end_time) %> </strong>
</div>
<br>
<div class="row span12">
  <em>Total Spots:</em> <strong><%= @slot.spots %> </strong>
</div>
<br>
<div class="row span12">
  <em>Spots Available:</em> <strong><%= @slot.available_spots %> </strong>
</div>
<br>
<% if current_user.admin? %>
<div class="row span5">
  <%= link_to 'Edit', edit_slot_path(@slot) %> |
  <%= link_to 'Back', slots_path %>
</div>
<% end %>
<hr class="style-four">
<input type="hidden" id="slotDate" value=<%= @slot.date %>>
<input type="hidden" id="slotTime" value=<%= @slot.start_time %>>
<!--<div class="container">-->
  <!--<div class="span10 offset1">-->
  <div class="span10">
    <table class="table table-condensed table-striped" id="tblSlot">
      <thead>
        <th>Name</th>
        <% if current_user.admin? %> <th>email</th> <% end %>
        <th>Ride Completed</th>
        <th>Status</th>
    </thead>
    <tbody>
      <% @riders.each_with_index do |r, i| %>
          <tr>
              <td><%= r.user.name %></td>
              <% if current_user.admin? %><td><%= r.user.email %></td><% end %>
              <td><%= r.user.completed_rides %></td>
              <td><%= r.user.get_slot_state(params[:id])%></td>
          </tr>
      <% end %>
      <% @waiting.each_with_index do |w, i| %>
        <tr>
          <td><%= w.user.name %></td>
          <% if current_user.admin? %><td><%= w.user.email %></td><% end %>
          <td><%= w.user.completed_rides %></td>
          <td><%= w.user.get_slot_state(params[:id])%></td>
        </tr>
    <% end %>
      </tbody>
      </table>
       <br>
    <br>
        <%= form_for @slot do |u|%>
            <% if signed_up?%>
                <%= u.submit "Remove Me", :class => "btn btn-primary", :id => "btnSession"  %>
            <% else %>
                <% if @slot.available_spots == 0 %>
                    <%= u.submit "Join Waiting List", :class => "btn btn-primary", :id => "btnSession" %>
                <% else %>
                    <%= u.submit "Add Me", :class => "btn btn-primary", :id => "btnSession" %>
                <% end %>
            <% end %>
            <% if current_user.admin? %>-or- <%= link_to "add/remove a rider","#", :id => "btnAdminAddUser", :class => "btn btn-primary"  %><% end %>
        <% end %>
        <% if current_user.admin? %><%= render 'admin_add_user'%><% end %>

  </div>
<!--</div>-->