config/routes.rb
GottaFit::Application.routes.draw do

  get "wait_lists/new"

  get "wait_lists/edit"

  get "wait_lists/index"

  get "slots/new"
  get "slots/calendar"
  get "slots/edit"

  get "slots/create"

  get "slots/destroy"

  get "slots/index"

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users
  resources :slots
  resources :password_resets
  match '/calendars(/:year(/:month))' => 'calendars#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get "static_pages/help"
  get "static_pages/about"

  root :to => 'static_pages#home'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete
  match '/user/:id/confirm/:confirm_code', :to =>'users#confirm'
  match '/users/:id', :via => :post, :to => 'users#edit'
  match '/schedule',  :to => 'slots#index'
  match '/schedule/:view', :to => 'slots#index'

end

app/views/shared/_errors.html.erb
<% if object.errors.any?%>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_login.html.erb
<%= form_for(:session, url: sessions_path) do |f| %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
<% end %>

<p>New user? <%= link_to "Sign Up Now!", signup_path %></p>
<p><%= link_to "forgotten password?", new_password_reset_path %></p>

app/views/shared/_message.html.erb
<div class="well">
    <h1>
      Welcome to the Tri Fit Lab's Multi-rider Sign-up<br>
    </h1>
    <% if !signed_in? %>
        <div class="span5 offset3">
            <%= link_to "Sign in!", '/signin', id: "btnLoginMain", class: "btn btn-primary" %> or
            <%= link_to "Sign up!", '/signup', class: "btn btn-primary" %>
        </div>
    <% end %>
</div>
  <div class="row-fluid">
    <div class="row-fluid">
      <div class="span4">
        <h2>Who are we?</h2>
        <p>TriFitLab is the go-to spot for Rhode Island and Massachusetts Triathletes,
          Time trialists, and cyclists, brought to you by <%= link_to 'TTBikeFit', 'http://www.ttbikefit.com' %>.
        </p>
      </div><!--/span-->
      <div class="span4">
        <h2>Multi-Rider Sessions</h2>
        <p>
          Tired of training alone? Sign up for a session in
          the "Pain Cave" and bring your friends!
        </p>
      </div><!--/span-->
      <div class="span4">
        <h2>Indoor Time Trials</h2>
        <p>Not enough competition in the winter?  We held 2 indoor time trials this
          past winter, the First Annual St Valentines Day Massacre and St. Patrick's Day
          Indoor Time Trial</p>
      </div><!--/span-->
    </div><!--/row-->
  </div>
<div id="frmLogin" title="Login">
  <%= render 'shared/login' %>
</div>

app/views/shared/_ride_details.html.erb
<h3>Upcoming Rides</h3> <br>
<% current_user.rides.each do |s| %>
    <% if s.date.to_date.future? || s.date.to_date.today?%>
        <span class="content">
         <%= link_to showday(s.date), s %>
         <ul>
         <li>start time: <%= showtime(s.start_time) %></li>
         <li>end time: <%= showtime(s.end_time) %></li>
         </ul>
        </span>
   <% end %>
<% end %>



app/views/shared/_stats.html.erb
<h3>User Stats</h3> <br>
<span>
  <ul>
  <li>Purchases Rides Remaining: <%= current_user.purchased_rides %></li>
  <li>Rides Completed: <%= current_user.completed_rides  %> </li>
  <li>Upcoming rides: <%= current_user.upcoming_rides %> </li>
  </ul>
</span>

app/views/shared/_user_info.html.erb
<h1>
  <%= current_user.first_name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>