config/routes.rb
GottaFit::Application.routes.draw do

  get "wait_lists/new"

  get "wait_lists/edit"

  get "wait_lists/index"

  get "slots/new"
  get "slots/calendar"
  get "slots/edit"

  get "slots/create"

  get "slots/destroy"

  get "slots/index"

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users
  resources :slots
  resources :password_resets
  match '/calendars(/:year(/:month))' => 'calendars#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get "static_pages/help"
  get "static_pages/about"

  root :to => 'static_pages#home'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete
  match '/user/:id/confirm/:confirm_code', :to =>'users#confirm'
  match '/users/:id', :via => :post, :to => 'users#edit'
  match '/schedule',  :to => 'slots#index'
  match '/schedule/:view', :to => 'slots#index'

end

app/views/layouts/_footer.html.erb
<div class="span10">
<footer>
  <small>
    <blockquote><p>'Till the roof comes off, till the lights go out'</p>
        <i>Marshall Bruce Mathers III</i>
    </blockquote>
  </small>
  <nav>
    <ul>
      <li>
        <%= link_to "Sign out", signout_path, :method => "delete" %>
      </li>
      <li><%= link_to "About Us",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top" >
  <div class="navbar-inner">
    <!--<div class="container">-->
    <div class="container-fluid">
      <nav>


        <ul class="nav pull-left">
          <li><%= link_to image_tag("/assets/img.jpg", :size => '35x35'), root_path %></li>
          <li><%= link_to "Home", root_path%></li>
          <li><%= link_to "Multi-rider Sessions", '/schedule/weekly' %></li>

          <% if !signed_in? %>
              <li><%= link_to "Sign in!", '/signin', :id => "btnLogin" %> </li>
          <% else %>
            <% if current_user.admin? %>
              <li><%= link_to "Users", users_path %></li>
            <% end %>
           <li><%= link_to "Sign Out", signout_path, :method => "delete" %></li>
          <% end %>
          <li><%= link_to "Help", '#', :id => 'btnHelp' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>
<div id="frmHelp" title="Help">
    <p>Some help stuff</p>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/themes/cupertino/jquery-ui.css",
                          "application", :media => "all" %>
  <%= javascript_include_tag "application","http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/jquery-ui.min.js" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <!--Google Analytics Script Begin-->
  <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-31413530-2']);
      _gaq.push(['_setDomainName', 'gottafit.com']);
      _gaq.push(['_trackPageview']);

      (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  </script>
  <!--Google Analytics Script End-->
</head>
<body>
<%= render 'layouts/header' %>
<div class="container-fluid">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, :id => "flash_message",:class => "alert alert-#{key}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
<%= debug(params) if Rails.env.development? %>
</body>
</html>